---
version: "3.8"
services:

  wiremock:
    build:
      context: ./infrastructure/docker/wiremock
      dockerfile: WireMockDockerfile
    ports:
      - target: 8080
        published: 8089
    networks:
      basic-service-spark-network:
        aliases:
          - wiremock

networks:
  basic-service-spark-network: